
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/your_database_name
      KAFKA_BROKER: kafka:9093 # Replace with actual Kafka broker address

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"  # Adjust port if needed
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: wp-clone  # Replace with your database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Change the password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092  # Ensure OUTSIDE is set to the correct address
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092  # Listeners set to 0.0.0.0 for binding to all interfaces
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

volumes:
  postgres_data: {}  # Persistent storage for Postgres data
